version: "3.9"  # optional since v1.27.0
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "5000:8080"
      - "50000:22"
    volumes:
      - /home/ubuntu/jenkins/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $(which docker):$(which docker)
